//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.02 at 03:26:02 PM JST 
//


package org.voltdb.compiler.deploymentfile;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for clusterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="clusterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="hostcount" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
 *       &lt;attribute name="sitesperhost" type="{http://www.w3.org/2001/XMLSchema}int" default="8" />
 *       &lt;attribute name="kfactor" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute name="elastic" type="{http://www.w3.org/2001/XMLSchema}string" default="enabled" />
 *       &lt;attribute name="schema" type="{}schemaType" default="ddl" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "clusterType")
public class ClusterType {

    @XmlAttribute(name = "hostcount")
    protected Integer hostcount;
    @XmlAttribute(name = "sitesperhost")
    protected Integer sitesperhost;
    @XmlAttribute(name = "kfactor")
    protected Integer kfactor;
    @XmlAttribute(name = "elastic")
    protected String elastic;
    @XmlAttribute(name = "schema")
    protected SchemaType schema;

    /**
     * Gets the value of the hostcount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getHostcount() {
        if (hostcount == null) {
            return  1;
        } else {
            return hostcount;
        }
    }

    /**
     * Sets the value of the hostcount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHostcount(Integer value) {
        this.hostcount = value;
    }

    /**
     * Gets the value of the sitesperhost property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getSitesperhost() {
        if (sitesperhost == null) {
            return  8;
        } else {
            return sitesperhost;
        }
    }

    /**
     * Sets the value of the sitesperhost property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSitesperhost(Integer value) {
        this.sitesperhost = value;
    }

    /**
     * Gets the value of the kfactor property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getKfactor() {
        if (kfactor == null) {
            return  0;
        } else {
            return kfactor;
        }
    }

    /**
     * Sets the value of the kfactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setKfactor(Integer value) {
        this.kfactor = value;
    }

    /**
     * Gets the value of the elastic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElastic() {
        if (elastic == null) {
            return "enabled";
        } else {
            return elastic;
        }
    }

    /**
     * Sets the value of the elastic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElastic(String value) {
        this.elastic = value;
    }

    /**
     * Gets the value of the schema property.
     * 
     * @return
     *     possible object is
     *     {@link SchemaType }
     *     
     */
    public SchemaType getSchema() {
        if (schema == null) {
            return SchemaType.DDL;
        } else {
            return schema;
        }
    }

    /**
     * Sets the value of the schema property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchemaType }
     *     
     */
    public void setSchema(SchemaType value) {
        this.schema = value;
    }

}
