//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.02 at 03:26:02 PM JST 
//


package org.voltdb.compiler.deploymentfile;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for pathsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pathsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="voltdbroot" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="path" type="{http://www.w3.org/2001/XMLSchema}string" default="voltdbroot" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="snapshots" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="path" type="{http://www.w3.org/2001/XMLSchema}string" default="snapshots" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="exportoverflow" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="path" type="{http://www.w3.org/2001/XMLSchema}string" default="export_overflow" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="commandlog" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="path" type="{http://www.w3.org/2001/XMLSchema}string" default="command_log" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="commandlogsnapshot" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="path" type="{http://www.w3.org/2001/XMLSchema}string" default="command_log_snapshot" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pathsType", propOrder = {

})
public class PathsType {

    protected PathsType.Voltdbroot voltdbroot;
    protected PathsType.Snapshots snapshots;
    protected PathsType.Exportoverflow exportoverflow;
    protected PathsType.Commandlog commandlog;
    protected PathsType.Commandlogsnapshot commandlogsnapshot;

    /**
     * Gets the value of the voltdbroot property.
     * 
     * @return
     *     possible object is
     *     {@link PathsType.Voltdbroot }
     *     
     */
    public PathsType.Voltdbroot getVoltdbroot() {
        return voltdbroot;
    }

    /**
     * Sets the value of the voltdbroot property.
     * 
     * @param value
     *     allowed object is
     *     {@link PathsType.Voltdbroot }
     *     
     */
    public void setVoltdbroot(PathsType.Voltdbroot value) {
        this.voltdbroot = value;
    }

    /**
     * Gets the value of the snapshots property.
     * 
     * @return
     *     possible object is
     *     {@link PathsType.Snapshots }
     *     
     */
    public PathsType.Snapshots getSnapshots() {
        return snapshots;
    }

    /**
     * Sets the value of the snapshots property.
     * 
     * @param value
     *     allowed object is
     *     {@link PathsType.Snapshots }
     *     
     */
    public void setSnapshots(PathsType.Snapshots value) {
        this.snapshots = value;
    }

    /**
     * Gets the value of the exportoverflow property.
     * 
     * @return
     *     possible object is
     *     {@link PathsType.Exportoverflow }
     *     
     */
    public PathsType.Exportoverflow getExportoverflow() {
        return exportoverflow;
    }

    /**
     * Sets the value of the exportoverflow property.
     * 
     * @param value
     *     allowed object is
     *     {@link PathsType.Exportoverflow }
     *     
     */
    public void setExportoverflow(PathsType.Exportoverflow value) {
        this.exportoverflow = value;
    }

    /**
     * Gets the value of the commandlog property.
     * 
     * @return
     *     possible object is
     *     {@link PathsType.Commandlog }
     *     
     */
    public PathsType.Commandlog getCommandlog() {
        return commandlog;
    }

    /**
     * Sets the value of the commandlog property.
     * 
     * @param value
     *     allowed object is
     *     {@link PathsType.Commandlog }
     *     
     */
    public void setCommandlog(PathsType.Commandlog value) {
        this.commandlog = value;
    }

    /**
     * Gets the value of the commandlogsnapshot property.
     * 
     * @return
     *     possible object is
     *     {@link PathsType.Commandlogsnapshot }
     *     
     */
    public PathsType.Commandlogsnapshot getCommandlogsnapshot() {
        return commandlogsnapshot;
    }

    /**
     * Sets the value of the commandlogsnapshot property.
     * 
     * @param value
     *     allowed object is
     *     {@link PathsType.Commandlogsnapshot }
     *     
     */
    public void setCommandlogsnapshot(PathsType.Commandlogsnapshot value) {
        this.commandlogsnapshot = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="path" type="{http://www.w3.org/2001/XMLSchema}string" default="command_log" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Commandlog {

        @XmlAttribute(name = "path")
        protected String path;

        /**
         * Gets the value of the path property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPath() {
            if (path == null) {
                return "command_log";
            } else {
                return path;
            }
        }

        /**
         * Sets the value of the path property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPath(String value) {
            this.path = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="path" type="{http://www.w3.org/2001/XMLSchema}string" default="command_log_snapshot" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Commandlogsnapshot {

        @XmlAttribute(name = "path")
        protected String path;

        /**
         * Gets the value of the path property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPath() {
            if (path == null) {
                return "command_log_snapshot";
            } else {
                return path;
            }
        }

        /**
         * Sets the value of the path property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPath(String value) {
            this.path = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="path" type="{http://www.w3.org/2001/XMLSchema}string" default="export_overflow" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Exportoverflow {

        @XmlAttribute(name = "path")
        protected String path;

        /**
         * Gets the value of the path property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPath() {
            if (path == null) {
                return "export_overflow";
            } else {
                return path;
            }
        }

        /**
         * Sets the value of the path property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPath(String value) {
            this.path = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="path" type="{http://www.w3.org/2001/XMLSchema}string" default="snapshots" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Snapshots {

        @XmlAttribute(name = "path")
        protected String path;

        /**
         * Gets the value of the path property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPath() {
            if (path == null) {
                return "snapshots";
            } else {
                return path;
            }
        }

        /**
         * Sets the value of the path property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPath(String value) {
            this.path = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="path" type="{http://www.w3.org/2001/XMLSchema}string" default="voltdbroot" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Voltdbroot {

        @XmlAttribute(name = "path")
        protected String path;

        /**
         * Gets the value of the path property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPath() {
            if (path == null) {
                return "voltdbroot";
            } else {
                return path;
            }
        }

        /**
         * Sets the value of the path property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPath(String value) {
            this.path = value;
        }

    }

}
