//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.02 at 03:26:02 PM JST 
//


package org.voltdb.compiler.deploymentfile;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServerExportEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ServerExportEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="file"/>
 *     &lt;enumeration value="jdbc"/>
 *     &lt;enumeration value="kafka"/>
 *     &lt;enumeration value="http"/>
 *     &lt;enumeration value="rabbitmq"/>
 *     &lt;enumeration value="custom"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ServerExportEnum")
@XmlEnum
public enum ServerExportEnum {

    @XmlEnumValue("file")
    FILE("file"),
    @XmlEnumValue("jdbc")
    JDBC("jdbc"),
    @XmlEnumValue("kafka")
    KAFKA("kafka"),
    @XmlEnumValue("http")
    HTTP("http"),
    @XmlEnumValue("rabbitmq")
    RABBITMQ("rabbitmq"),
    @XmlEnumValue("custom")
    CUSTOM("custom");
    private final String value;

    ServerExportEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ServerExportEnum fromValue(String v) {
        for (ServerExportEnum c: ServerExportEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
