/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_voltdb_jni_ExecutionEngine */

#ifndef _Included_org_voltdb_jni_ExecutionEngine
#define _Included_org_voltdb_jni_ExecutionEngine
#ifdef __cplusplus
extern "C" {
#endif
#undef org_voltdb_jni_ExecutionEngine_ERRORCODE_SUCCESS
#define org_voltdb_jni_ExecutionEngine_ERRORCODE_SUCCESS 0L
#undef org_voltdb_jni_ExecutionEngine_ERRORCODE_ERROR
#define org_voltdb_jni_ExecutionEngine_ERRORCODE_ERROR 1L
#undef org_voltdb_jni_ExecutionEngine_ERRORCODE_WRONG_SERIALIZED_BYTES
#define org_voltdb_jni_ExecutionEngine_ERRORCODE_WRONG_SERIALIZED_BYTES 101L
#undef org_voltdb_jni_ExecutionEngine_ERRORCODE_NEED_PLAN
#define org_voltdb_jni_ExecutionEngine_ERRORCODE_NEED_PLAN 110L
#undef org_voltdb_jni_ExecutionEngine_ERRORCODE_PROGRESS_UPDATE
#define org_voltdb_jni_ExecutionEngine_ERRORCODE_PROGRESS_UPDATE 111L
#undef org_voltdb_jni_ExecutionEngine_ERRORCODE_DECODE_BASE64_AND_DECOMPRESS
#define org_voltdb_jni_ExecutionEngine_ERRORCODE_DECODE_BASE64_AND_DECOMPRESS 112L
#undef org_voltdb_jni_ExecutionEngine_EE_PLAN_CACHE_SIZE
#define org_voltdb_jni_ExecutionEngine_EE_PLAN_CACHE_SIZE 1000L
#undef org_voltdb_jni_ExecutionEngine_LONG_OP_THRESHOLD
#define org_voltdb_jni_ExecutionEngine_LONG_OP_THRESHOLD 10000LL
/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nextDependencyTest
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_voltdb_jni_ExecutionEngine_nextDependencyTest
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeCreate
 * Signature: (Z)J
 */
JNIEXPORT jlong JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeCreate
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeDestroy
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeDestroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeInitialize
 * Signature: (JIJII[BJI)I
 */
JNIEXPORT jint JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeInitialize
  (JNIEnv *, jobject, jlong, jint, jlong, jint, jint, jbyteArray, jlong, jint);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeSetBuffers
 * Signature: (JLjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeSetBuffers
  (JNIEnv *, jobject, jlong, jobject, jint, jobject, jint, jobject, jint);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeLoadCatalog
 * Signature: (JJ[B)I
 */
JNIEXPORT jint JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeLoadCatalog
  (JNIEnv *, jobject, jlong, jlong, jbyteArray);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeUpdateCatalog
 * Signature: (JJ[B)I
 */
JNIEXPORT jint JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeUpdateCatalog
  (JNIEnv *, jobject, jlong, jlong, jbyteArray);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeLoadTable
 * Signature: (JI[BJJJZZJ)I
 */
JNIEXPORT jint JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeLoadTable
  (JNIEnv *, jobject, jlong, jint, jbyteArray, jlong, jlong, jlong, jboolean, jboolean, jlong);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeExecutePlanFragments
 * Signature: (JI[J[JJJJJJ)I
 */
JNIEXPORT jint JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeExecutePlanFragments
  (JNIEnv *, jobject, jlong, jint, jlongArray, jlongArray, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeSerializeTable
 * Signature: (JILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeSerializeTable
  (JNIEnv *, jobject, jlong, jint, jobject, jint);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeTick
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeTick
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeQuiesce
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeQuiesce
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeGetStats
 * Signature: (JI[IZJ)I
 */
JNIEXPORT jint JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeGetStats
  (JNIEnv *, jobject, jlong, jint, jintArray, jboolean, jlong);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeToggleProfiler
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeToggleProfiler
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeHashinate
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeHashinate
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeUpdateHashinator
 * Signature: (JIJI)V
 */
JNIEXPORT void JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeUpdateHashinator
  (JNIEnv *, jobject, jlong, jint, jlong, jint);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeGetThreadLocalPoolAllocations
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeGetThreadLocalPoolAllocations
  (JNIEnv *, jclass);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeSetUndoToken
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeSetUndoToken
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeReleaseUndoToken
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeReleaseUndoToken
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeUndoUndoToken
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeUndoUndoToken
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeSetLogLevels
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeSetLogLevels
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeActivateTableStream
 * Signature: (JIIJ[B)Z
 */
JNIEXPORT jboolean JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeActivateTableStream
  (JNIEnv *, jobject, jlong, jint, jint, jlong, jbyteArray);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeTableStreamSerializeMore
 * Signature: (JII[B)J
 */
JNIEXPORT jlong JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeTableStreamSerializeMore
  (JNIEnv *, jobject, jlong, jint, jint, jbyteArray);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeProcessRecoveryMessage
 * Signature: (JJII)V
 */
JNIEXPORT void JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeProcessRecoveryMessage
  (JNIEnv *, jobject, jlong, jlong, jint, jint);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeTableHashCode
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeTableHashCode
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeExecuteTask
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeExecuteTask
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeExportAction
 * Signature: (JZJJ[B)J
 */
JNIEXPORT jlong JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeExportAction
  (JNIEnv *, jobject, jlong, jboolean, jlong, jlong, jbyteArray);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeGetUSOForExportTable
 * Signature: (J[B)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeGetUSOForExportTable
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeGetRSS
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeGetRSS
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
