/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_voltcore_utils_DBBPool */

#ifndef _Included_org_voltcore_utils_DBBPool
#define _Included_org_voltcore_utils_DBBPool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_voltcore_utils_DBBPool
 * Method:    getBufferCRC32C
 * Signature: (Ljava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_org_voltcore_utils_DBBPool_getBufferCRC32C
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     org_voltcore_utils_DBBPool
 * Method:    getCRC32C
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_org_voltcore_utils_DBBPool_getCRC32C
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_voltcore_utils_DBBPool
 * Method:    getBufferCRC32
 * Signature: (Ljava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_org_voltcore_utils_DBBPool_getBufferCRC32
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     org_voltcore_utils_DBBPool
 * Method:    getCRC32
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_org_voltcore_utils_DBBPool_getCRC32
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_voltcore_utils_DBBPool
 * Method:    getMurmur3128
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_org_voltcore_utils_DBBPool_getMurmur3128__JII
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_voltcore_utils_DBBPool
 * Method:    getMurmur3128
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_voltcore_utils_DBBPool_getMurmur3128__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_voltcore_utils_DBBPool
 * Method:    nativeDeleteCharArrayMemory
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_voltcore_utils_DBBPool_nativeDeleteCharArrayMemory
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_voltcore_utils_DBBPool
 * Method:    nativeAllocateUnsafeByteBuffer
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_voltcore_utils_DBBPool_nativeAllocateUnsafeByteBuffer
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
